import React, { Component } from "react";
import { View, Text, ScrollView, StyleSheet } from "react-native";
import Header from "../../components/Header";
import { height, width } from "../../components/Colors";

const Report = () => {
  const text =
    "orem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.";

  return (
    <ScrollView style={{ flex: 1 }}>
      <Header />
      <View style={{ paddingHorizontal: width / 20 }}>
        <Text
          style={{
            fontSize: 22,
            alignSelf: "center",
            fontWeight: "bold",
            marginBottom: height / 60,
          }}
        >
          Medical Report
        </Text>
        <View>
          <Text style={styles.titles}>Medecine & Prescription</Text>
          <Text style={styles.text}>{text}</Text>
        </View>
        <View>
          <Text style={styles.titles}>Medical & Lab Tests</Text>
          <Text style={styles.text}>{text}</Text>
        </View>
        <View>
          <Text style={styles.titles}>Medecal Treatment & recommendations</Text>
          <Text style={styles.text}>{text}</Text>
        </View>
        <View>
          <Text style={styles.titles}>
            Medecine & General Checkups result generated by Ai
          </Text>
          <Text style={styles.text}>{text}</Text>
        </View>
        <View>
          <Text style={styles.titles}>Disease pathology for family</Text>
          <Text style={styles.text}>{text}</Text>
        </View>
      </View>
    </ScrollView>
  );
};
const styles = StyleSheet.create({
  titles: {
    fontSize: 20,
    fontWeight: "700",
    alignSelf: "flex-start",
  },
  text: {
    fontSize: 15,
    fontWeight: "300",
    textAlign: "left",
    paddingVertical: height / 50,
  },
});
export default Report;
